name: youtube_player_iframe
description: Flutter port of the official YouTube iFrame player API. Supports web & mobile platforms.
version: 1.1.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

  # flutter_inappwebview: '>=4.0.0 <5.0.0'
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter